### ISSUE TITLE
Binaries Data

### ISSUE THREAD

**Issue by widoz** [inpsyde/search-and-replace#110]
There is an issue with binaries data. Them are removed in https://github.com/inpsyde/search-and-replace/commit/b817c69c8b04e2bcdde1458bc3530e42a327e150 

Are no longer necessary? 

Because assignment and logic remains https://github.com/inpsyde/search-and-replace/blob/master/inc/Database/Exporter.php#L443

**Comment by bueltge** [comment]
I think is an mistake. In the tests was ok, no problems, but no unittests that show us the problem in the deep.
The point to change this was this post https://medium.com/websec/wordpress-and-recursive-unserialize-5518b124b23b and his contact. But I changed only short and fast this function and get a lot of errors, so that I was not in deep dive inside the source.

**Comment by widoz** [comment]
I'll add again the binaries, but may you have a look at the `recursive_unserialize_replace` ? I'm not sure about the issue with the serialized data.

**Comment by bueltge** [comment]
Have you this function inside the tests? This function was the point that we need an deep test about s/r for serialized data.

**Comment by widoz** [comment]
Yup, here https://github.com/inpsyde/search-and-replace/blob/master/tests/UnitTests/Database/ReplaceTest.php#L348 with a data provider, so I can add more strings.

**Comment by bueltge** [comment]
Great, again and again, it is great to see the work. :heart:

**Comment by widoz** [comment]
Reintroduced the binaries data. I close this one and create a new regarding the serialized issue, so we have a place where discuss that in order to prevent the bug will be introduced again.

**Comment by widoz** [comment]
New ref about the serialize bug: https://github.com/inpsyde/search-and-replace/issues/114
