### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dlong500** [inpsyde/search-and-replace#118]
It appears there hasn't been a release of this plugin since late 2016 despite numerous commits since then.  Is there going to be a new release published to the Wordpress plugin registry?

**Comment by bvdv** [comment]
Hi @bueltge,

I'd like to help with new release.

Here some preliminary ToDo list what I can\should to do.

1) About autoloader, there is commit https://github.com/inpsyde/search-and-replace/commit/df2bb4b28313b98051ff0b700e82bfbf89aa1260 about vendor and composer. If I understand correctly current idea is to generate autoloader with command like `composer dump-autoload -o --no-dev` and then include `vendor` folder to new release zip file? If yes, should I do it? 

2)  Update readme.txt, CHANGELOG.md, README.md with descriptions new features like: Added CSV format alternative for search/replace, Added Multiline searching.

3)After you check my last pull request https://github.com/inpsyde/search-and-replace/pull/124 what else I should to do for new release, please inform me.

**Comment by bueltge** [comment]
Great, the list should have all tasks. After create a zip package please create a tag, upload also this zip to use them without composer knowledge. The zip package should run after upload in each wp install, done. After this I will upload to w.org.

**Comment by bvdv** [comment]
Hi @bueltge,

sorry for my late reply.

Could you please check pre-release - [https://github.com/bvdv/search-and-replace/releases](https://github.com/bvdv/search-and-replace/releases )
Please check for files structure, content and main direction in which I should will done it.

What I've done:
1) Added `inpsyde-search-replace.min.css` and `inpsyde-search-replace.min.js`
2) Corrected readme.txt
3) `composer dump-autoload -o --no-dev` because it need autoloader.php and after that I archived it and install from zip.
4) Tested main features via UI.  

ToDo:
1) There is discussion https://github.com/inpsyde/search-and-replace/issues/114 about function `recursive_unserialize_replace`, maybe it will affect on current master branch. 
2) I still in commits checking and some testing, because there are some amount commits since 3.1.2, to me hard to decide what should to be deleted and what should remain, for example should be deleted all code related to `l10n`?

Please after checking let inform me what else I need to do.

**Comment by bueltge** [comment]
Sorry @bvdv I will do that, currently only to much topics for to less time. But not forgotten.

**Comment by bvdv** [comment]
@bueltge No worries, whenever you can.

**Comment by bueltge** [comment]
Thanks for all of your work, especially @widoz and @bvdv :heart: 
The new release is live, see forward inside the support forum for issues ;)
