### ISSUE TITLE
Set default charset to utf8mb4

### ISSUE THREAD

**Issue by ryantang333** [inpsyde/search-and-replace#91]
I ran into an issue with some data of mine where the mysql dump didn't run because of utf8. It was easily fixable by setting the DB_CHARSET in wp-config.php, however, it might be worth it to default to utf8mb4 (for those without DB_CHARSET defined) as I believe it's what utf8 should be in mysql.

**Comment by bueltge** [comment]
Fixed with #92 

Thanks a lot @ryantang333
Have you used the master branch version for s/r test in your environment? Currently we have a lot of changes in this branch, especially in the search&replace of serialized data and it would be fine, if you can help us to test this. Is an important change for more security. All other tools and plugins in this context have the same source base with the same security problem.
